### ISSUE TITLE
Getting TargetCloseError

### ISSUE THREAD

**Issue by kaheidt** [thejoeosborne/puppeteer-extra-lambda#1]
I'm getting the below error when I try to deploy your code as-is to Lambda, and I'm curious if you've seen this before. It's specifically happening on the line `const page: Page = await browser.newPage();`. Reading online, there are suggestions that my lambda isn't set to enough memory to handle the chrome instance, but I bumped it to 4000MB and still got the error.
```
2024-09-05T23:45:09.088Z	828223ae-3e27-4466-8b11-78aa900e561b	INFO	Error in Lambda Handler: TargetCloseError: Protocol error (Target.createTarget): Target closed
    at CallbackRegistry.clear (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72:36)
    at #onClose (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:164:25)
    at WebSocket.<anonymous> (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:49:30)
    at callListener (/function/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/function/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:520:28)
    at WebSocket.emitClose (/function/node_modules/ws/lib/websocket.js:272:10)
    at Socket.socketOnClose (/function/node_modules/ws/lib/websocket.js:1341:15)
    at Socket.emit (node:events:520:28)
    at TCP.<anonymous> (node:net:338:12) {
  cause: ProtocolError
      at <instance_members_initializer> (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
      at new Callback (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
      at CallbackRegistry.create (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
      at Connection._rawSend (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)
      at Connection.send (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:21)
      at CdpBrowser._createPageInContext (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:180:53)
      at CdpBrowser._createPageInContext (/function/node_modules/puppeteer-extra/dist/index.cjs.js:210:51)
      at CdpBrowserContext.newPage (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/BrowserContext.js:115:40)
      at async CdpBrowser.newPage (/function/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:177:16)
      at async Runtime.handler (/function/dist/index.js:41:22)
```

**Comment by ysoares0209** [comment]
hey @kaheidt 

I'm not sure if this is the best of solving this, but if it helps I managed to fix this same issue on my end:

1 - I removed the `--disable-gpu` flag
2 - I increased `memorySize` to 2048 & timeout to 900 (probably an overkill)
3 - I changed the `executablePath` to ` ".cache/puppeteer/chrome-headless-shell/linux-132.0.6834.83/chrome-headless-shell-linux64/chrome-headless-shell";` - Again, not sure if this will cause issues down the line, but so far it has worked as expected
